import React from 'react';

const TermsContent: React.FC = () => {
  return (
    <div>
      <p className="!mt-0">
        <strong>Last Updated: {new Date().toLocaleDateString()}</strong>
      </p>
      <p>
        Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the Domain Trend Analyzer website (the "Service") operated by us.
      </p>
      <p>
        Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
      </p>
      
      <h3>1. Use of Service</h3>
      <p>
        You agree not to use the Service for any unlawful purpose or any purpose prohibited under this clause. You agree not to use the Service in any way that could damage the Service or the general business of Domain Trend Analyzer.
      </p>
      <p>
        The Service is provided for informational purposes only. The analysis and domain suggestions generated by our AI are not financial or investment advice. You are solely responsible for your own decisions and actions based on the use of this Service.
      </p>

      <h3>2. Intellectual Property</h3>
      <p>
        The Service and its original content, features, and functionality are and will remain the exclusive property of Domain Trend Analyzer and its licensors.
      </p>

      <h3>3. Limitation of Liability</h3>
      <p>
        In no event shall Domain Trend Analyzer, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
      </p>

      <h3>4. Changes</h3>
      <p>
        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide reasonable notice prior to any new terms taking effect.
      </p>
      
      <p className="p-4 bg-red-900/50 border border-red-500 rounded-md mt-6">
        <em><strong>Disclaimer for AdSense Approval:</strong> This is a placeholder Terms of Service agreement. It is <strong>NOT</strong> legal advice. You should consult with a legal professional to draft a comprehensive Terms of Service agreement that fits your specific business needs and legal requirements.</em>
      </p>
    </div>
  );
};

export default TermsContent;
